import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { useAuth0 } from "@auth0/auth0-react";
import GenreFilter from "./GenreFilter";
import StatusFilter from "./StatusFilter";
import SearchBar from "./SearchBar";
import SortButton from "./SortButton";
import NavBar from "./NavBar";
import api from "../services/api";
import { getBooks, getBookCounts } from "../services/bookService";
import "../assets/bookkeeper.css";